### ISSUE TITLE
phplist `loginname` character limit.

### ISSUE THREAD

**Issue by nfebe** [phpList/phplist-plugin-simplesaml#2]
# Backstory

The following steps are followed to give a user access to phplist via SSO.

- authenticate with IdP
- Return to phplist
- Check if user exist
- If not, create the user

The snippet that checks for an existing user looks as follows:

```php
 $admindata = Sql_Fetch_Assoc_Query(sprintf('select loginname,password,disabled,id from %s where loginname="%s"', $GLOBALS["tables"]["admin"], addslashes($login)));
            // if not found, then we create it
            if (!$admindata) {
                // create a new record

               Sql_Query(sprintf(
                    'insert into %s (loginname,namelc,created,privileges) values("%s","%s",now(),"%s")',
                    $GLOBALS["tables"]["admin"],
                    addslashes($login),
                    addslashes($login),
                    sql_escape($privileges)
                ));
}
```

This code would always attempt to create new user and return :

```
duplicate entry 'G-c526ae09-f072-4401-86eb' for key 'loginname'
```

### Why?

After investigations I found out the `IdP` returns a `NameID` of the fomat `G-c526ae09-f072-4401-86eb**************` in this case `G-c526ae09-f072-4401-86eb-9ca7a3817a3a` BUT phplist `loginname` apparently can only be 25 characters long.

Hence, it truncates the `NameID` when creating the user for the first time and when it comes to searching it would never find that user again and would attempt to create a new user which would lead to the same truncation and hence a duplicate.

![phplist_admin_db_view](https://user-images.githubusercontent.com/14317775/161458924-1b5c31e4-a5dc-474d-9a55-511aca9e4fb4.png)

### Possible Solutions

- Truncate the `NameID` to 25 characters to make the comparison work, this method is risky because the first 25 characters of the `NameID` might be identical for more than one user.
- Do a collision free harsh that converts to `<= 25` characters and store the harsh instead
- Update the phplist database to accept more than 25 characters.

NB :  Keycloak (the IdP in this case) does not provide any other unique identifyiing information such as email. Configuring the `NameIDPolicy` to request for `emails` caused keycloak to complain instead of showing the login page, forcing keycloak to return emails from it's configuration caused the `simpelsamlphp` installation to fail. So, `NameID` is really the only the we have got.

**Comment by aulona1** [comment]
> Truncate the NameID to 25 characters to make the comparison work, this method is risky because the first 25 characters of the NameID might be identical for more than one user.

MO I'd avoid a method which we know that can cause problems in the future. We want it to be optimized as much as possible.

> Do a collision free harsh that converts to <= 25 characters and store the harsh instead
This could be a possible solution.

> Update the phplist database to accept more than 25 characters.
So in this phase the loginname it works correctly with less than 25 characters, right? 
@michield Would be helpful to share your thoughts on this.

> NB : Keycloak (the IdP in this case) does not provide any other unique identifyiing information such as email. Configuring the NameIDPolicy...

Found these discussions related to this issue, you might have probably seen them but sharing the links here anyway. Maybe can help as a reference.
https://github.com/keycloak/keycloak/discussions/8839 
https://github.com/sventorben/keycloak-home-idp-discovery

Also I have a question regarding the login. 
Again you might previously discussed this with Michiel but considering that I don't know many details on this project, if  you could kindly provide some information on this :

Is it going to work (if yes, how) sso to one/multiple phplist accounts using user credentials stored on another phplist account?

**Comment by aulona1** [comment]
> Truncate the NameID to 25 characters to make the comparison work, this method is risky because the first 25 characters of the NameID might be identical for more than one user.

IMO, I'd avoid a method which we know that can cause problems in the future. We want it to be optimized as much as possible.

   
>  Do a collision free harsh that converts to <= 25 characters and store the harsh instead

This could be a possible solution.

  
>   Update the phplist database to accept more than 25 characters.

So in this phase the loginname it works correctly with less than 25 characters, right?
@michield Would be helpful to share your thoughts on this.

>     NB : Keycloak (the IdP in this case) does not provide any other unique identifyiing information such as email. Configuring the NameIDPolicy...

Found these discussions related to this issue, you might have probably seen them but sharing the links here anyway. Maybe can help as a reference.
https://github.com/keycloak/keycloak/discussions/8839
https://github.com/sventorben/keycloak-home-idp-discovery

Also I have a question regarding the login.
Again you might previously discussed this with Michiel but considering that I don't know many details on this project, if you could kindly provide some information on this :

_- Is it going to work (if yes, how) sso to one/multiple phplist accounts using user credentials stored on another phplist account?_

**Comment by nfebe** [comment]
> - Is it going to work (if yes, how) sso to one/multiple phplist accounts using user credentials stored on another phplist account?

Not sure what you are asking.

**Comment by aulona1** [comment]
It's ok to ignore the question, since phplist doesn't allow to have multiple accounts with the same email. 

How is it going with the steps above. 
Is there something I can help you with ?

**Comment by michield** [comment]
I think the hash idea is good, except that a sha256 hash is 60 characters and even an md5 one is longer than 25.

So, I think we want to combine the two.  The UUID you get back is 39 characters, but it may be that some are longer, so we can't rely on that. So, we update the DB to allow 65 characters and store the sha256 hash of the UUID. The hash will always be the same length, so that is more reliable. 

Do you think that will work? So the plan is to do two things:

1. increase the size of the column to 66
2. store the sha256 and use it for comparison

**Comment by nfebe** [comment]
@michield If we increase the size of the column to 66, we might not need to `SHA` it..... So updating the DB column to accept upto 66 chars is `+1`.

The identification returned is usually 38 chars (`G-c526ae09-f072-4401-86eb-9ca7a3817a3a`)

**Comment by michield** [comment]
ok, also, just to be clear, the "namelc" column is the same as login, but all lowercase, so you'd need to do something like "strtolower(addslashes($login))" on that column.

I presume we should increase the size of both columns?

**Comment by nfebe** [comment]
Sounds like the right thing to do!

By the way, realized `namelc` is set to `VAR(255)` so there's no issue with that.
